project_name: sample
db_password: password
user: user
memory_limit: 128M
upload_limit: 64M
proxy_template_name: default.conf.template
proxy_port: 18000

hostname: "{{ ansible_hostname }}.local"
host_ip: "{{ ansible_default_ipv4.address }}"
