services:
  proxy:
    # platform: linux/x86_64
    build:
      context: ./proxy
    container_name: ${PROJECT_NAME}-proxy
    ports:
      - ${PROXY_PUBLIC_PORT}:80
    depends_on:
      - python
    volumes:
      - ./proxy/${PROXY_TEMPLATE_NAME}:/etc/nginx/conf.d/default.conf.template
      - ./proxy/log/:/var/log/nginx/
      - ./proxy/ssl/:/etc/nginx/ssl/
    environment:
      APP_NAME: ${PROJECT_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
      # PROXY_PUBLIC_PORT: ${PROXY_PUBLIC_PORT}
      HOSTNAME: ${HOSTNAME}
    # 環境変数を渡す
    command: /bin/sh -c "envsubst '$$PROJECT_NAME $$HOSTNAME' \
      < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf \
      && nginx -g 'daemon off;'"
    hostname: ${HOSTNAME}
    # コンテナ内の/etc/hostsのIPとホスト名を紐づけたい場合はアンコメントアウト
    extra_hosts:
      - "${HOSTNAME}:${HOST_IP}" # 環境変数を使用
  python:
    build:
      context: ./python
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        USER: ${USER}
        PASSWORD: ${DB_PASSWORD}
    container_name: ${APP_NAME}-python
    ports:
      - ${PYTHON_PORT}:8000
    expose:
      - 8000
    volumes:
      - ./python/html/:/var/www/html
    tty: true
    environment:
      PASSWORD: ${DB_PASSWORD}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
